"""`Laya`: the public entry point (DEVELOPMENT_PLAN.md §10).

    from laya_apple import Laya
    laya = Laya.from_pretrained("convaiinnovations/laya-typed-decisions")
    result = laya.predict(context="...", questions={...})
    result.answers, result.runtime

Two execution modes:

- execution="inline" (default): the backends live in this process and requests run one
  at a time per instance. Routing is the v0.1 rule (routing.decide).
- execution="workers": each device's backend runs in its own worker process
  (laya_apple.executor), so the GPU and the ANE serve requests concurrently without the
  in-process interference measured in research/v0.2-concurrency. `predict` may be called
  from many threads; `submit` returns a Future and `apredict` is awaitable. Routing is
  queue-aware (scheduling.decide_queued), and identical to v0.1 on an idle machine.
"""

from __future__ import annotations

import asyncio
import json
import threading
import time
import warnings
from concurrent.futures import Future
from pathlib import Path

from . import routing, scheduling
from .artifacts import platform_profile, profile_matches
from .errors import (
    ArtifactMissingError,
    BackendUnavailableError,
    InvalidRequestError,
    LayaAppleError,
)
from .hub import checkpoint_path, verify_weights
from .prompt import Calibration, Tokenizer, format_answers, prepare
from .registry import ANE_COMPUTE_UNITS, ANE_PRECISION, ModelSpec, resolve, routing_table
from .result import Result, RuntimeInfo

EXECUTIONS = ("inline", "workers")
ANE_PLACEMENTS = ("auto", "thread", "process")


def ane_placement_for(model: str) -> str:
    """Measured per-model ANE placement for execution="workers" (laya_apple/data/placement.json,
    generated by scripts/derive_placement.py from benchmarks/v0.2/placement-*.json)."""
    from importlib import resources

    table = json.loads(resources.files("laya_apple.data").joinpath("placement.json").read_text())
    return table["models"][model]["ane"]


def _coremltools_available() -> bool:
    try:
        import coremltools  # noqa: F401
    except ImportError:
        return False
    return True


def platform_validated(profile: dict | None = None) -> bool:
    profile = profile or platform_profile()
    return any(profile_matches(profile, p) for p in routing_table().get("validated_profiles", []))


class _GPUView:
    """Parent-side identity of an MLX worker (for RuntimeInfo)."""

    name, device = "mlx", "gpu"

    def __init__(self, spec: ModelSpec, dtype: str):
        self.spec, self.dtype = spec, dtype

    def artifact_revision(self, items) -> str:
        return f"mlx:{self.spec.weights_sha256[:12]}:{self.dtype}"


class Laya:
    """A loaded checkpoint plus the backends its `device` setting allows."""

    def __init__(
        self,
        spec: ModelSpec,
        checkpoint: Path,
        device: str,
        *,
        dtype: str,
        batch_size: int,
        execution: str = "inline",
        ane_placement: str = "auto",
    ):
        if device not in routing.DEVICES:
            raise ValueError(f"device must be one of {routing.DEVICES}, got {device!r}")
        if execution not in EXECUTIONS:
            raise ValueError(f"execution must be one of {EXECUTIONS}, got {execution!r}")
        self.spec, self.checkpoint, self.device, self.dtype = spec, checkpoint, device, dtype
        self.execution = execution
        if ane_placement not in ANE_PLACEMENTS:
            raise ValueError(f"ane_placement must be one of {ANE_PLACEMENTS}, got {ane_placement!r}")
        self.ane_placement = ane_placement_for(spec.name) if ane_placement == "auto" else ane_placement
        self.config = json.loads((checkpoint / "rl_agent_config.json").read_text())
        self._encoder_cfg = json.loads((checkpoint / "encoder/config.json").read_text())
        self.tokenizer = Tokenizer(checkpoint / "tokenizer")
        self.calibration = Calibration(self.config)
        self.mlx = self.ane = None  # backends (inline) or parent-side views (workers)
        self._workers: dict = {}
        self._tie_buckets: tuple = ()
        self._service = scheduling.ServiceModel(routing_table()["models"][spec.name]["service_ms"])
        self.ane_state = routing.AneState(routing.RUNTIME_UNAVAILABLE)
        # Inline: one request at a time per instance; Core ML predictions and MLX graph
        # evaluation on a shared model are not documented as re-entrant.
        self._lock = threading.Lock()
        self._closed = False
        self._ane_dead_warned = False
        try:
            if execution == "inline":
                self._start_inline(batch_size)
            else:
                self._start_workers(batch_size)
        except BaseException:
            self.close()
            raise

    # ------------------------------------------------------------------ construction

    @classmethod
    def from_pretrained(
        cls,
        model_id: str,
        device: str = "auto",
        *,
        dtype: str = "float16",
        local_files_only: bool = False,
        batch_size: int = 16,
        execution: str = "inline",
        ane_placement: str = "auto",
    ) -> "Laya":
        """Load a pinned checkpoint.

        device="gpu": MLX only. device="ane": validated Core ML artifacts only; requests
        they cannot serve raise. device="auto": MLX, plus the ANE for the validated short
        single-question path when its artifacts are present and verified (§7.2).
        execution="workers" serves both devices concurrently (heterogeneous execution): MLX
        in a worker process, Core ML either on a thread in this process or in a worker
        process. ane_placement="auto" uses the measured per-model choice.
        """
        if device not in routing.DEVICES:
            raise ValueError(f"device must be one of {routing.DEVICES}, got {device!r}")
        if execution not in EXECUTIONS:
            raise ValueError(f"execution must be one of {EXECUTIONS}, got {execution!r}")
        spec = resolve(model_id)
        path = checkpoint_path(spec, local_files_only=local_files_only)
        verify_weights(spec, path)
        return cls(
            spec, path, device, dtype=dtype, batch_size=batch_size, execution=execution, ane_placement=ane_placement
        )

    def _ane_gate(self) -> str | None:
        """Why auto cannot use the ANE here, or None."""
        if not _coremltools_available():
            return routing.RUNTIME_UNAVAILABLE
        if not platform_validated():
            return routing.PLATFORM_NOT_VALIDATED
        return None

    def _warn_rejected(self, load_errors: dict):
        for b, e in load_errors.items():
            if not isinstance(e, ArtifactMissingError):
                warnings.warn(
                    f"laya-apple: ANE artifact {self.spec.name} L{b} rejected ({type(e).__name__}: {e}); "
                    "auto routes these requests to MLX",
                    RuntimeWarning,
                    stacklevel=5,
                )

    def _start_inline(self, batch_size):
        if self.device in ("auto", "gpu"):
            from .backends.mlx import MLXBackend

            self.mlx = MLXBackend(
                self.spec, self.checkpoint, self.tokenizer.pad_token_id, dtype=self.dtype, batch_size=batch_size
            )
        if self.device == "ane":
            self.ane = self._load_ane_inline(self.spec.ane_buckets, strict=True)
            self.ane_state = routing.AneState(None, self.ane.buckets)
        elif self.device == "auto":
            if not self.spec.auto_ane_buckets:
                self.ane_state = routing.AneState(None, ())
            elif (why := self._ane_gate()) is not None:
                self.ane_state = routing.AneState(why)
            else:
                self.ane = self._load_ane_inline(self.spec.auto_ane_buckets, strict=False)
                self._warn_rejected(self.ane.load_errors)
                if not self.ane.models:
                    self.ane = None
                self.ane_state = routing.AneState(None, self.ane.buckets if self.ane else ())

    def _load_ane_inline(self, buckets, *, strict):
        if not _coremltools_available():
            raise BackendUnavailableError(
                "device='ane' needs coremltools: install the [ane] extra (uv sync --extra ane)"
            )
        from .backends.coreml_ane import ANEBackend

        return ANEBackend(
            self.spec,
            self.checkpoint,
            self.tokenizer.pad_token_id,
            int(self._encoder_cfg["local_attention"]),
            buckets,
            strict=strict,
        )

    def _start_workers(self, batch_size):
        from .backends.coreml_ane import ANEShapes
        from .executor import DeviceWorker

        common = {"model": self.spec.name, "checkpoint": str(self.checkpoint), "pad_id": self.tokenizer.pad_token_id}
        want_ane = self.device == "ane"
        if self.device == "auto":
            if not self.spec.ane_buckets:
                self.ane_state = routing.AneState(None, ())
            elif (why := self._ane_gate()) is not None:
                self.ane_state = routing.AneState(why)
            else:
                want_ane = True
        elif self.device == "ane" and not _coremltools_available():
            raise BackendUnavailableError(
                "device='ane' needs coremltools: install the [ane] extra (uv sync --extra ane)"
            )
        # Launch every worker first, then wait: the devices load in parallel.
        if want_ane:
            ane_args = dict(
                common,
                local_attention=int(self._encoder_cfg["local_attention"]),
                buckets=list(self.spec.ane_buckets),  # auto also loads the tie band for queue-aware routing
                strict=self.device == "ane",
            )
            self._workers["ane"] = DeviceWorker("ane", ane_args, placement=self.ane_placement, wait=False)
        if self.device in ("auto", "gpu"):
            gpu_args = dict(common, dtype=self.dtype, batch_size=batch_size)
            self._workers["gpu"] = DeviceWorker("gpu", gpu_args, placement="process", wait=False)
        for w in self._workers.values():
            w.wait_ready()
        if "gpu" in self._workers:
            self.mlx = _GPUView(self.spec, self.dtype)
        if want_ane:
            worker = self._workers["ane"]
            info = worker.info
            load_errors = {int(b): e for b, e in info["load_errors"].items()}
            shapes = ANEShapes(
                self.spec, info["offered"], {int(b): h for b, h in info["artifact_sha256"].items()}, load_errors
            )
            if self.device == "auto":
                self._warn_rejected(load_errors)
            if shapes.buckets:
                self.ane = shapes
                auto = tuple(b for b in shapes.buckets if b in self.spec.auto_ane_buckets)
                self._tie_buckets = tuple(b for b in shapes.buckets if b not in self.spec.auto_ane_buckets)
                self.ane_state = routing.AneState(None, auto if self.device == "auto" else shapes.buckets)
            else:
                self._workers.pop("ane").close()
                self.ane_state = routing.AneState(None, ())

    # ------------------------------------------------------------------ lifecycle

    def close(self):
        """Stop worker processes (workers mode). Safe to call more than once."""
        if self._closed:
            return
        self._closed = True
        for w in self._workers.values():
            try:
                w.close()
            except Exception:
                pass
        self._workers = {}

    def __enter__(self):
        return self

    def __exit__(self, *exc):
        self.close()

    def __del__(self):
        try:
            self.close()
        except Exception:
            pass

    # ------------------------------------------------------------------ inference

    def backlogs(self) -> tuple[float, float]:
        """(gpu, ane) backlog estimates in ms; zeros in inline mode."""
        g = self._workers["gpu"].backlog_ms() if "gpu" in self._workers else 0.0
        a = self._workers["ane"].backlog_ms() if "ane" in self._workers else 0.0
        return g, a

    def route(self, prepared, backlogs: tuple[float, float] | None = None) -> routing.Decision:
        if self.execution == "inline":
            return routing.decide(
                self.device, self.spec, prepared.question_count, prepared.sequence_length, self.ane_state
            )
        gpu_backlog, ane_backlog = backlogs if backlogs is not None else self.backlogs()
        ane_state = self.ane_state
        worker = self._workers.get("ane")
        if self.device == "auto" and worker is not None and not worker.alive:
            # A dead ANE worker is reported, never hidden: auto records the reason on every
            # result and warns once; explicit device="ane" requests keep raising.
            if not self._ane_dead_warned:
                self._ane_dead_warned = True
                warnings.warn(
                    "laya-apple: the ANE worker exited; auto routes to MLX (ane_runtime_unavailable)",
                    RuntimeWarning,
                    stacklevel=3,
                )
            ane_state = routing.AneState(routing.RUNTIME_UNAVAILABLE)
        return scheduling.decide_queued(
            self.device,
            self.spec,
            prepared.question_count,
            prepared.sequence_length,
            ane_state,
            service=self._service,
            gpu_backlog_ms=gpu_backlog,
            ane_backlog_ms=ane_backlog,
            tie_buckets=self._tie_buckets,
        )

    def prepare(self, context, questions):
        return prepare(self.tokenizer, self.config, context, questions)

    @staticmethod
    def _request(context, questions, state):
        if state is not None:
            if context is not None:
                raise InvalidRequestError("pass context or state, not both")
            context = state
        if context is None:
            context = ""
        if questions is None:
            raise InvalidRequestError("questions are required")
        return context, questions

    def predict(self, context=None, questions=None, *, state=None) -> Result:
        """Answer `questions` about `context` (upstream calls it `state`; either works)."""
        if self.execution == "workers":
            return self.submit(context, questions, state=state).result()
        context, questions = self._request(context, questions, state)
        t0 = time.perf_counter()
        prep = self.prepare(context, questions)
        decision = self.route(prep)
        backend = self.ane if decision.target == "ane" else self.mlx
        if backend is None:  # unreachable by construction; never substitute another device
            raise LayaAppleError(f"internal routing error: {decision}")
        buckets = ()
        with self._lock:
            if decision.target == "ane":
                buckets = tuple(backend.check(prep.items))  # raises before any work runs
            logits, act = backend.forward(prep.items)
        return self._result(prep, decision, backend, buckets, logits, act, t0)

    def submit(self, context=None, questions=None, *, state=None) -> Future:
        """Queue a request; the Future resolves to a Result or raises the request's error."""
        if self.execution == "inline":
            fut: Future = Future()
            try:
                fut.set_result(self.predict(context, questions, state=state))
            except BaseException as e:
                fut.set_exception(e)
            return fut
        if self._closed:
            raise BackendUnavailableError("this Laya instance is closed")
        context, questions = self._request(context, questions, state)
        t0 = time.perf_counter()
        prep = self.prepare(context, questions)
        gpu_backlog, ane_backlog = self.backlogs()
        decision = self.route(prep, (gpu_backlog, ane_backlog))
        backend = self.ane if decision.target == "ane" else self.mlx
        worker = self._workers.get(decision.target)
        if backend is None or worker is None:  # unreachable by construction; never substitute
            raise LayaAppleError(f"internal routing error: {decision}")
        buckets = ()
        if decision.target == "ane":
            buckets = tuple(backend.check(prep.items))  # raises before any work is queued
            estimate = sum(self._service.ane_ms(b) for b in buckets)
        else:
            estimate = self._service.gpu_ms(prep.sequence_length, prep.question_count)
        out: Future = Future()
        queue_state = {"gpu_backlog_ms": gpu_backlog, "ane_backlog_ms": ane_backlog}

        def finish(done: Future):
            try:
                logits, act, wait_ms, device_ms = done.result()
                out.set_result(
                    self._result(
                        prep,
                        decision,
                        backend,
                        buckets,
                        logits,
                        act,
                        t0,
                        wait_ms=wait_ms,
                        device_ms=device_ms,
                        **queue_state,
                    )
                )
            except BaseException as e:
                out.set_exception(e)

        worker.submit(prep.items, estimate).add_done_callback(finish)
        return out

    async def apredict(self, context=None, questions=None, *, state=None) -> Result:
        """Awaitable predict (workers mode runs concurrently; inline mode runs in a thread)."""
        if self.execution == "inline":
            return await asyncio.to_thread(self.predict, context, questions, state=state)
        return await asyncio.wrap_future(self.submit(context, questions, state=state))

    def _result(
        self,
        prep,
        decision,
        backend,
        buckets,
        logits,
        act,
        t0,
        *,
        wait_ms=None,
        device_ms=None,
        gpu_backlog_ms=None,
        ane_backlog_ms=None,
    ) -> Result:
        answers = format_answers(prep, logits, act, self.calibration)
        runtime = RuntimeInfo(
            backend=backend.name,
            device=backend.device,
            model=self.spec.name,
            model_revision=self.spec.revision,
            sequence_length=prep.sequence_length,
            question_count=prep.question_count,
            routing_reason=decision.reason,
            artifact_revision=backend.artifact_revision(prep.items),
            latency_ms=(time.perf_counter() - t0) * 1000,
            compute_units=ANE_COMPUTE_UNITS if decision.target == "ane" else None,
            buckets=buckets,
            dtype=ANE_PRECISION if decision.target == "ane" else self.dtype,
            execution=self.execution,
            queue_wait_ms=wait_ms,
            device_ms=device_ms,
            gpu_backlog_ms=gpu_backlog_ms,
            ane_backlog_ms=ane_backlog_ms,
        )
        return Result(answers=answers, usage={"input_tokens": prep.input_tokens, "output_tokens": 0}, runtime=runtime)

    def info(self) -> dict:
        return {
            "model": self.spec.name,
            "repo": self.spec.repo,
            "revision": self.spec.revision,
            "device": self.device,
            "execution": self.execution,
            "ane_placement": self.ane_placement if self.execution == "workers" else None,
            "dtype": self.dtype,
            "mlx": self.mlx is not None,
            "ane_buckets": list(self.ane.buckets) if self.ane else [],
            "ane_load_errors": {
                str(b): f"{type(e).__name__}: {e}" for b, e in (self.ane.load_errors.items() if self.ane else [])
            },
            "auto_ane": {
                "unavailable": self.ane_state.unavailable,
                "buckets": list(self.ane_state.buckets),
                "tie_buckets": list(self._tie_buckets),
            },
        }
