"""Build markdown tables in reports/ from the raw JSON/JSONL data.

    uv run python scripts/report.py parity
    uv run python scripts/report.py latency
    uv run python scripts/report.py crossover
    uv run python scripts/report.py concurrency --input raw/concurrency/<file>.json
"""

from __future__ import annotations

import argparse
import json
import sys
from collections import defaultdict
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).parent))
from common import RAW, REPORTS, read_jsonl  # noqa: E402

MODELS = ["laya", "laya-multilingual", "laya-typed-decisions"]


def cfg_label(spec: dict, describe: dict | None = None) -> str:
    b = spec["backend"]
    if b == "torch":
        return f"PyTorch {spec.get('device', 'cpu').upper()} FP32"
    if b == "mlx":
        return f"MLX GPU {'FP16' if spec.get('dtype', 'float16') == 'float16' else 'FP32'}"
    units = {"cpu_only": "CPU_ONLY", "cpu_gpu": "CPU_AND_GPU", "cpu_ne": "CPU_AND_NE", "all": "ALL"}[
        spec.get("units", "cpu_gpu")
    ]
    if b == "coreml":
        return f"Core ML ordinary {'enumerated' if spec.get('enumerated') else 'fixed'} · {units}"
    return f"Core ML ANE-graph ({spec.get('variant', 'masked')}) · {units}"


# ----------------------------------------------------------------------------- parity


def g(x):
    """Format a metric that may have been stored as "nan"/"inf" (non-finite output)."""
    return x if isinstance(x, str) else f"{x:.3g}"


def parity():
    lines = ["# Parity support matrix", "", "Generated by `scripts/report.py parity` from `raw/parity/`.", ""]
    lines += [
        "Legend: ✅ pass · ⚠️ passes the gate with near-tie flips · ❌ fails the gate · — not applicable.",
        "`prob` = max calibrated-probability |Δ| vs upstream PyTorch CPU FP32; `mism` = decision",
        "mismatches (hard / all). Tolerances in methodology.md §5.",
        "",
    ]
    for model in MODELS:
        d = RAW / "parity" / model
        if not d.exists():
            continue
        runs = [json.loads(p.read_text()) for p in sorted(d.glob("*.json"))]
        lines += [f"## {model}", ""]
        lengths = sorted(
            {k for r in runs for k in (r.get("summary") or {}).get("by_length", {})},
            key=lambda x: (not x.isdigit(), int(x) if x.isdigit() else 0, x),
        )
        head = "| configuration | verdict | prob max | action prob max | logit max | mism hard/all | repeat | " + " | ".join(
            f"L{x}" if x.isdigit() else x for x in lengths
        ) + " |"
        lines += [head, "|" + "---|" * (7 + len(lengths))]
        for r in sorted(runs, key=lambda r: cfg_label(r["spec"])):
            s = r.get("summary")
            if not s:
                lines.append(f"| {cfg_label(r['spec'])} | ❌ {r.get('status')}: {str(r.get('error'))[:80]} |")
                continue
            verdict = "✅" if r["passed"] and not s["near_tie_flips"] else ("⚠️" if r["passed"] else "❌")
            cells = []
            for L in lengths:
                c = s["by_length"].get(L)
                if not c:
                    cells.append("—")
                    continue
                pm = c["prob_max_abs"]
                ok = c["hard_mismatches"] == 0 and not isinstance(pm, str) and pm <= r["tolerance"]["probability"]
                cells.append(f"{'✅' if ok else '❌'} {g(pm)}" + (f" ({c['mismatches']}✗)" if c["mismatches"] else ""))
            lines.append(
                f"| {cfg_label(r['spec'])} | {verdict} | {g(s['prob_max_abs'])} | {g(s['action_prob_max_abs'])} | "
                f"{g(s['logit_max_abs'])} | {s['decision_mismatches_outside_near_tie']}/{s['decision_mismatches']} | "
                f"{'yes' if r.get('repeat_identical') else 'NO'} | " + " | ".join(cells) + " |"
            )
        lines.append("")
    out = REPORTS / "parity-matrix.md"
    out.parent.mkdir(exist_ok=True)
    out.write_text("\n".join(lines) + "\n")
    print(out)


# ----------------------------------------------------------------------------- latency


def latency_rows(tag=None):
    p = RAW / "bench" / "latency.jsonl"
    rows = read_jsonl(p) if p.exists() else []
    return [r for r in rows if tag is None or r.get("tag") == tag]


def latency():
    rows = latency_rows()
    by = defaultdict(list)
    for r in rows:
        by[(r["model"], cfg_label(r["spec"]), r["questions"], r["tag"])].append(r)
    lines = ["# Latency (model-only `forward` and end-to-end `predict`)", "",
             "Generated by `scripts/report.py latency` from `raw/bench/latency.jsonl`. Milliseconds.", ""]
    for model in MODELS:
        mrows = [r for r in rows if r["model"] == model]
        if not mrows:
            continue
        lines += [f"## {model}", ""]
        lengths = sorted({r["length"] for r in mrows})
        for q in sorted({r["questions"] for r in mrows}):
            lines += [f"### {q} question(s) per request — forward P50 / P95 (pass A)", ""]
            lines += ["| configuration | " + " | ".join(f"L{L}" for L in lengths) + " |", "|" + "---|" * (1 + len(lengths))]
            cfgs = sorted({cfg_label(r["spec"]) for r in mrows if r["questions"] == q})
            for c in cfgs:
                cells = []
                for L in lengths:
                    hit = [r for r in mrows if cfg_label(r["spec"]) == c and r["length"] == L and r["questions"] == q and r["tag"] == "pass-a" and "forward" in r]
                    cells.append(f"{hit[0]['forward']['p50_ms']:.2f} / {hit[0]['forward']['p95_ms']:.2f}" if hit else "—")
                lines.append(f"| {c} | " + " | ".join(cells) + " |")
            lines.append("")
        # end-to-end and tails for q=1
        lines += ["### 1 question — end-to-end predict P50 / P95 / P99, mean (pass A)", ""]
        lines += ["| configuration | " + " | ".join(f"L{L}" for L in lengths) + " |", "|" + "---|" * (1 + len(lengths))]
        for c in sorted({cfg_label(r["spec"]) for r in mrows if "predict" in r}):
            cells = []
            for L in lengths:
                hit = [r for r in mrows if cfg_label(r["spec"]) == c and r["length"] == L and r["questions"] == 1 and r["tag"] == "pass-a" and "predict" in r]
                if hit:
                    p = hit[0]["predict"]
                    cells.append(f"{p['p50_ms']:.2f} / {p['p95_ms']:.2f} / {p['p99_ms']:.2f}, {p['mean_ms']:.2f}")
                else:
                    cells.append("—")
            lines.append(f"| {c} | " + " | ".join(cells) + " |")
        lines.append("")
        # drift: pass A vs pass B
        pb = [r for r in mrows if r["tag"] == "pass-b"]
        if pb:
            lines += ["### Order control — forward P50, pass A vs pass B (reversed order), 1 question", ""]
            lines += ["| configuration | L | pass A | pass B | Δ % |", "|---|---:|---:|---:|---:|"]
            for r in sorted(pb, key=lambda r: (cfg_label(r["spec"]), r["length"])):
                a = [x for x in mrows if x["tag"] == "pass-a" and x["spec"] == r["spec"] and x["length"] == r["length"] and x["questions"] == 1]
                if a:
                    pa, pbv = a[0]["forward"]["p50_ms"], r["forward"]["p50_ms"]
                    lines.append(f"| {cfg_label(r['spec'])} | {r['length']} | {pa:.2f} | {pbv:.2f} | {100 * (pbv - pa) / pa:+.1f} |")
            lines.append("")
        # cold init + memory
        lines += ["### Cold initialisation and memory (1 question, first length of each process)", ""]
        lines += ["| configuration | L | load s | first call ms | RSS after run MiB | framework peak MiB |", "|---|---:|---:|---:|---:|---:|"]
        seen = set()
        for r in sorted(mrows, key=lambda r: (cfg_label(r["spec"]), r["length"])):
            key = (cfg_label(r["spec"]), r["length"])
            if r["questions"] != 1 or r["tag"] != "pass-a" or key in seen:
                continue
            seen.add(key)
            mem = r["memory"]
            fw = mem.get("mlx_peak") or mem.get("mps_driver_allocated")
            lines.append(
                f"| {key[0]} | {r['length']} | {r['cold']['load_s']:.1f} | {r['cold']['first_forward_ms']:.1f} | "
                f"{mem['rss'] / 2**20:.0f} | {fw / 2**20 if fw else float('nan'):.0f} |"
            )
        lines.append("")
    out = REPORTS / "latency.md"
    out.parent.mkdir(exist_ok=True)
    out.write_text("\n".join(lines) + "\n")
    print(out)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("what", choices=["parity", "latency"])
    args = ap.parse_args()
    {"parity": parity, "latency": latency}[args.what]()


if __name__ == "__main__":
    main()
