"""Build markdown tables in reports/ from the raw JSON/JSONL data.

    uv run python scripts/report.py parity
    uv run python scripts/report.py latency
    uv run python scripts/report.py crossover
    uv run python scripts/report.py concurrency --input raw/concurrency/<file>.json
"""

from __future__ import annotations

import argparse
import json
import sys
from collections import defaultdict
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).parent))
from common import RAW, REPORTS, read_jsonl  # noqa: E402

MODELS = ["laya", "laya-multilingual", "laya-typed-decisions"]


def cfg_label(spec: dict, describe: dict | None = None) -> str:
    b = spec["backend"]
    if b == "torch":
        return f"PyTorch {spec.get('device', 'cpu').upper()} FP32"
    if b == "mlx":
        return f"MLX GPU {'FP16' if spec.get('dtype', 'float16') == 'float16' else 'FP32'}"
    units = {"cpu_only": "CPU_ONLY", "cpu_gpu": "CPU_AND_GPU", "cpu_ne": "CPU_AND_NE", "all": "ALL"}[
        spec.get("units", "cpu_gpu")
    ]
    if b == "coreml":
        return f"Core ML ordinary {'enumerated' if spec.get('enumerated') else 'fixed'} · {units}"
    return f"Core ML ANE-graph ({spec.get('variant', 'masked')}) · {units}"


# ----------------------------------------------------------------------------- parity


def g(x):
    """Format a metric that may have been stored as "nan"/"inf" (non-finite output)."""
    return x if isinstance(x, str) else f"{x:.3g}"


def parity():
    lines = ["# Parity support matrix", "", "Generated by `scripts/report.py parity` from `raw/parity/`.", ""]
    lines += [
        "Legend: ✅ pass · ⚠️ passes the gate with near-tie flips · ❌ fails the gate · — not applicable.",
        "`prob` = max calibrated-probability |Δ| vs upstream PyTorch CPU FP32; `mism` = decision",
        "mismatches (hard / all). Tolerances in methodology.md §5.",
        "",
    ]
    for model in MODELS:
        d = RAW / "parity" / model
        if not d.exists():
            continue
        runs = [json.loads(p.read_text()) for p in sorted(d.glob("*.json"))]
        lines += [f"## {model}", ""]
        lengths = sorted(
            {k for r in runs for k in (r.get("summary") or {}).get("by_length", {})},
            key=lambda x: (not x.isdigit(), int(x) if x.isdigit() else 0, x),
        )
        head = "| configuration | verdict | prob max | action prob max | logit max | mism hard/all | repeat | " + " | ".join(
            f"L{x}" if x.isdigit() else x for x in lengths
        ) + " |"
        lines += [head, "|" + "---|" * (7 + len(lengths))]
        for r in sorted(runs, key=lambda r: cfg_label(r["spec"])):
            s = r.get("summary")
            if not s:
                lines.append(f"| {cfg_label(r['spec'])} | ❌ {r.get('status')}: {str(r.get('error'))[:80]} |")
                continue
            verdict = "✅" if r["passed"] and not s["near_tie_flips"] else ("⚠️" if r["passed"] else "❌")
            cells = []
            for L in lengths:
                c = s["by_length"].get(L)
                if not c:
                    cells.append("—")
                    continue
                pm = c["prob_max_abs"]
                ok = c["hard_mismatches"] == 0 and not isinstance(pm, str) and pm <= r["tolerance"]["probability"]
                cells.append(f"{'✅' if ok else '❌'} {g(pm)}" + (f" ({c['mismatches']}✗)" if c["mismatches"] else ""))
            lines.append(
                f"| {cfg_label(r['spec'])} | {verdict} | {g(s['prob_max_abs'])} | {g(s['action_prob_max_abs'])} | "
                f"{g(s['logit_max_abs'])} | {s['decision_mismatches_outside_near_tie']}/{s['decision_mismatches']} | "
                f"{'yes' if r.get('repeat_identical') else 'NO'} | " + " | ".join(cells) + " |"
            )
        lines.append("")
    out = REPORTS / "parity-matrix.md"
    out.parent.mkdir(exist_ok=True)
    out.write_text("\n".join(lines) + "\n")
    print(out)


# ----------------------------------------------------------------------------- latency


def latency_rows(tag=None):
    p = RAW / "bench" / "latency.jsonl"
    rows = read_jsonl(p) if p.exists() else []
    return [r for r in rows if tag is None or r.get("tag") == tag]


def latency():
    rows = latency_rows()
    by = defaultdict(list)
    for r in rows:
        by[(r["model"], cfg_label(r["spec"]), r["questions"], r["tag"])].append(r)
    lines = ["# Latency (model-only `forward` and end-to-end `predict`)", "",
             "Generated by `scripts/report.py latency` from `raw/bench/latency.jsonl`. Milliseconds.", ""]
    for model in MODELS:
        mrows = [r for r in rows if r["model"] == model]
        if not mrows:
            continue
        lines += [f"## {model}", ""]
        lengths = sorted({r["length"] for r in mrows})
        for q in sorted({r["questions"] for r in mrows}):
            lines += [f"### {q} question(s) per request — forward P50 / P95 (pass A)", ""]
            lines += ["| configuration | " + " | ".join(f"L{L}" for L in lengths) + " |", "|" + "---|" * (1 + len(lengths))]
            cfgs = sorted({cfg_label(r["spec"]) for r in mrows if r["questions"] == q})
            for c in cfgs:
                cells = []
                for L in lengths:
                    hit = [r for r in mrows if cfg_label(r["spec"]) == c and r["length"] == L and r["questions"] == q and r["tag"] == "pass-a" and "forward" in r]
                    cells.append(f"{hit[0]['forward']['p50_ms']:.2f} / {hit[0]['forward']['p95_ms']:.2f}" if hit else "—")
                lines.append(f"| {c} | " + " | ".join(cells) + " |")
            lines.append("")
        # end-to-end and tails for q=1
        lines += ["### 1 question — end-to-end predict P50 / P95 / P99, mean (pass A)", ""]
        lines += ["| configuration | " + " | ".join(f"L{L}" for L in lengths) + " |", "|" + "---|" * (1 + len(lengths))]
        for c in sorted({cfg_label(r["spec"]) for r in mrows if "predict" in r}):
            cells = []
            for L in lengths:
                hit = [r for r in mrows if cfg_label(r["spec"]) == c and r["length"] == L and r["questions"] == 1 and r["tag"] == "pass-a" and "predict" in r]
                if hit:
                    p = hit[0]["predict"]
                    cells.append(f"{p['p50_ms']:.2f} / {p['p95_ms']:.2f} / {p['p99_ms']:.2f}, {p['mean_ms']:.2f}")
                else:
                    cells.append("—")
            lines.append(f"| {c} | " + " | ".join(cells) + " |")
        lines.append("")
        # drift: pass A vs pass B
        pb = [r for r in mrows if r["tag"] == "pass-b"]
        if pb:
            lines += ["### Order control — forward P50, pass A vs pass B (reversed order), 1 question", ""]
            lines += ["| configuration | L | pass A | pass B | Δ % |", "|---|---:|---:|---:|---:|"]
            for r in sorted(pb, key=lambda r: (cfg_label(r["spec"]), r["length"])):
                a = [x for x in mrows if x["tag"] == "pass-a" and x["spec"] == r["spec"] and x["length"] == r["length"] and x["questions"] == 1]
                if a:
                    pa, pbv = a[0]["forward"]["p50_ms"], r["forward"]["p50_ms"]
                    lines.append(f"| {cfg_label(r['spec'])} | {r['length']} | {pa:.2f} | {pbv:.2f} | {100 * (pbv - pa) / pa:+.1f} |")
            lines.append("")
        # cold init + memory
        lines += ["### Cold initialisation and memory (1 question, first length of each process)", ""]
        lines += ["| configuration | L | load s | first call ms | RSS after run MiB | framework peak MiB |", "|---|---:|---:|---:|---:|---:|"]
        seen = set()
        for r in sorted(mrows, key=lambda r: (cfg_label(r["spec"]), r["length"])):
            key = (cfg_label(r["spec"]), r["length"])
            if r["questions"] != 1 or r["tag"] != "pass-a" or key in seen:
                continue
            seen.add(key)
            mem = r["memory"]
            fw = mem.get("mlx_peak") or mem.get("mps_driver_allocated")
            lines.append(
                f"| {key[0]} | {r['length']} | {r['cold']['load_s']:.1f} | {r['cold']['first_forward_ms']:.1f} | "
                f"{mem['rss'] / 2**20:.0f} | {fw / 2**20 if fw else float('nan'):.0f} |"
            )
        lines.append("")
    out = REPORTS / "latency.md"
    out.parent.mkdir(exist_ok=True)
    out.write_text("\n".join(lines) + "\n")
    print(out)


# ----------------------------------------------------------------------------- crossover


def _p50(rows, model, pred, L, q, tag=("pass-a", "refine"), mode="forward"):
    tags = (tag,) if isinstance(tag, str) else tag
    hit = [r for r in rows if r["model"] == model and pred(r["spec"]) and r["length"] == L
           and r["questions"] == q and r["tag"] in tags and mode in r]
    return hit[0][mode]["p50_ms"] if hit else None


def crossover_point(lengths, a, b):
    """First length where b becomes faster than a, log-log interpolated between samples."""
    pts = [(L, x, y) for L, x, y in zip(lengths, a, b) if x is not None and y is not None]
    for (L0, a0, b0), (L1, a1, b1) in zip(pts, pts[1:]):
        r0, r1 = np.log(a0 / b0), np.log(a1 / b1)  # >0 means b faster
        if r0 <= 0 < r1:
            t = -r0 / (r1 - r0)
            return float(np.exp(np.log(L0) + t * (np.log(L1) - np.log(L0))))
    return None


def crossover():
    rows = latency_rows()
    is_mlx = lambda s: s["backend"] == "mlx" and s.get("dtype", "float16") == "float16"  # noqa: E731
    is_ane = lambda s: s["backend"] == "ane" and s.get("units") == "cpu_ne" and s.get("batch", 1) == 1 and s.get("variant", "masked") == "masked"  # noqa: E731
    is_cmg = lambda s: s["backend"] == "coreml" and s.get("units") == "cpu_gpu" and not s.get("enumerated")  # noqa: E731
    out = {"generated_by": "scripts/report.py crossover", "models": {}}
    lines = ["# GPU / ANE crossover", "", "Forward (model-only) P50, pass A. Ratio > 1 means ANE is faster.", ""]
    for model in MODELS:
        Ls = sorted({r["length"] for r in rows if r["model"] == model and r["tag"] in ("pass-a", "refine")})
        if not Ls:
            continue
        lines += [f"## {model}", ""]
        out["models"][model] = {}
        for q in (1, 4, 8):
            mlx = [_p50(rows, model, is_mlx, L, q) for L in Ls]
            ane = [_p50(rows, model, is_ane, L, q) for L in Ls]
            cmg = [_p50(rows, model, is_cmg, L, q) for L in Ls]
            if not any(ane) or not any(mlx):
                continue
            x = crossover_point(Ls, ane, mlx)
            both = [(a, m) for a, m in zip(ane, mlx) if a is not None and m is not None]
            if x:
                verdict = "crossover ≈ L%.0f" % x
            elif all(a < m for a, m in both):
                verdict = "ANE faster at every measured length"
            else:
                verdict = "GPU faster at every measured length"
            out["models"][model][f"q{q}"] = {"lengths": Ls, "mlx_fp16": mlx, "ane_cpu_ne_b1": ane, "coreml_gpu_fixed": cmg, "crossover_length": x}
            lines += [f"### {q} question(s), ANE B=1 sequential vs MLX batched — {verdict}", ""]
            lines += ["| L | MLX FP16 | Core ML GPU (fixed) | ANE (CPU_AND_NE) | MLX/ANE | faster |", "|---:|---:|---:|---:|---:|---|"]
            for L, m, c, a in zip(Ls, mlx, cmg, ane):
                if m is None or a is None:
                    continue
                lines.append(f"| {L} | {m:.2f} | {c:.2f} | {a:.2f} | {m / a:.2f} | {'ANE' if a < m else 'GPU'} |" if c else f"| {L} | {m:.2f} | — | {a:.2f} | {m / a:.2f} | {'ANE' if a < m else 'GPU'} |")
            lines.append("")
        # batched ANE exports
        bat = [r for r in rows if r["model"] == model and r["tag"] == "batch"]
        if bat:
            lines += ["### Batched ANE exports (B questions in one Core ML call) vs MLX with the same question count", ""]
            lines += ["| B | L | ANE batched | ANE B=1 sequential | MLX FP16 | MLX/ANE-batched |", "|---:|---:|---:|---:|---:|---:|"]
            for r in sorted(bat, key=lambda r: (r["spec"]["batch"], r["length"])):
                B, L = r["spec"]["batch"], r["length"]
                m = _p50(rows, model, is_mlx, L, B)
                seq = _p50(rows, model, is_ane, L, B)
                a = r["forward"]["p50_ms"]
                lines.append(f"| {B} | {L} | {a:.2f} | {seq if seq is None else f'{seq:.2f}'} | {m if m is None else f'{m:.2f}'} | {(m / a) if m else float('nan'):.2f} |")
                out["models"][model].setdefault("batched", []).append({"batch": B, "length": L, "ane_batched": a, "ane_seq": seq, "mlx": m})
            lines.append("")
    (REPORTS / "crossover.md").write_text("\n".join(lines) + "\n")
    from common import save_json

    save_json(REPORTS / "crossover.json", out)
    print(REPORTS / "crossover.md")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("what", choices=["parity", "latency", "crossover"])
    args = ap.parse_args()
    {"parity": parity, "latency": latency, "crossover": crossover}[args.what]()


if __name__ == "__main__":
    main()
