"""Option-order robustness: laya-apple's `choice` decisions must not depend on criteria order.

`research/option-order/fixture.json` holds the upstream reference decisions (unmodified
Laya, torch CPU FP32) for a small subset of `research/option-order/cases.json`, generated by:

    cd research/phase-0-feasibility
    uv run python ../option-order/upstream.py --model laya-typed-decisions \\
        --output ../option-order/fixture.json

That fixture is not generated by this test suite (it needs the research venv's upstream
`laya` + torch, which this environment does not have); the test skips with a clear message
until it exists.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from laya_apple import Laya

ROOT = Path(__file__).resolve().parents[2]
FIXTURE_PATH = ROOT / "research/option-order/fixture.json"
CASES_PATH = ROOT / "research/option-order/cases.json"
SUBSET = ("route-c0", "sentiment-c1", "priority-c2", "action-c3", "category-c4")

pytestmark = pytest.mark.integration


def _load_fixture():
    if not FIXTURE_PATH.exists():
        pytest.skip(
            f"{FIXTURE_PATH} is missing; generate it with research/option-order/upstream.py "
            "from the research venv (see the module docstring) before running this test"
        )
    return json.loads(FIXTURE_PATH.read_text())


def _cases_by_name():
    cases = json.loads(CASES_PATH.read_text())["cases"]
    return {c["name"]: c for c in cases}


def _criteria_for(case, order):
    labels, values = case["labels"], case["values"]
    return {labels[i]: values[labels[i]] for i in order}


@pytest.fixture(scope="module")
def fixture_cases():
    data = _load_fixture()
    return {c["name"]: c for c in data["cases"] if c["name"] in SUBSET}


def test_mlx_decisions_match_upstream_per_permutation(fixture_cases, model_name):
    if model_name != "laya-typed-decisions":
        pytest.skip("fixture covers laya-typed-decisions only")
    all_cases = _cases_by_name()
    laya = Laya.from_pretrained(model_name, device="gpu", dtype="float32", local_files_only=True)
    try:
        for name in SUBSET:
            case, ref = all_cases[name], fixture_cases[name]
            ref_by_order = {tuple(p["order"]): p["chosen"] for p in ref["permutations"] if "chosen" in p}
            for order in case["permutations"]:
                crit = _criteria_for(case, order)
                questions = {"q": {"type": "choice", "instructions": case["instructions"], "criteria": crit}}
                result = laya.predict(context=case["context"], questions=questions)
                chosen = result.answers["q"]["choice"]
                expected = ref_by_order.get(tuple(order))
                if expected is not None:
                    assert chosen == expected, f"{name} order={order}: got {chosen!r}, upstream chose {expected!r}"
    finally:
        laya.close()


def test_mlx_is_permutation_consistent_where_upstream_is(fixture_cases, model_name):
    """No runtime-introduced instability: where upstream's decision is order-invariant,
    laya-apple's decision must be order-invariant too (not merely equal to upstream once)."""
    if model_name != "laya-typed-decisions":
        pytest.skip("fixture covers laya-typed-decisions only")
    all_cases = _cases_by_name()
    laya = Laya.from_pretrained(model_name, device="gpu", dtype="float32", local_files_only=True)
    try:
        for name in SUBSET:
            case, ref = all_cases[name], fixture_cases[name]
            if ref["decision_changed"]:
                continue  # upstream itself is unstable here; not a runtime claim to make
            chosen = set()
            for order in case["permutations"]:
                crit = _criteria_for(case, order)
                questions = {"q": {"type": "choice", "instructions": case["instructions"], "criteria": crit}}
                result = laya.predict(context=case["context"], questions=questions)
                chosen.add(result.answers["q"]["choice"])
            assert len(chosen) == 1, f"{name}: laya-apple decision changed under permutation but upstream's did not"
    finally:
        laya.close()
